# .gitlab-ci.yml
image: node:12.16.2

before_script:
  - yarn install --frozen-lockfile

pages:
  script:
  - yarn build
  - mv build public
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules/
    - .yarn
  only:
  - master

